services:
  db:
    image: ubuntu/mysql
    environment:
      MYSQL_USER: gw_user
      MYSQL_PASSWORD: gw_pass
      MYSQL_DATABASE: gw
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    ports:
      - "3306:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - app-network

  redis-cluster:
    image: redis:alpine
    # ports:
    #   - "6380-6382:6380-6382"
    volumes:
      - ./config/redis:/redis-conf:ro
    networks:
      - app-network
    command: sh /redis-conf/start.sh
    healthcheck:
      test: ["CMD", "/bin/sh", "/redis-conf/healthcheck.sh", "6380", "6381", "6382"]
      interval: 4s
      timeout: 5s
      retries: 5

  redis-proxy:
    image: envoyproxy/envoy:v1.38-latest
    ports:
      - "6379:6380"  # 代理端口
    volumes:
      - ./config/envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      redis-cluster:
        condition: service_healthy
        restart: true
    networks:
      - app-network
    command: ["-c", "/etc/envoy/envoy.yaml", "-l", "info"]

  socks5-proxy:
    image: xkuma/socks5
    ports:
      - "10080:1080"
    networks:
      - app-network

  kafka:
    image: redpandadata/redpanda:latest
    hostname: kafka
    command:
      - redpanda start
      - --mode dev-container
      - --smp 1
      - --memory 1G
      - --node-id 0
      - --kafka-addr internal://0.0.0.0:19092,external://0.0.0.0:9092
      - --advertise-kafka-addr internal://kafka:19092,external://localhost:9092
    ports:
      - "9092:9092"
      # - "18081:8081" # schema registry
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9095:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'local'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:19092'
    volumes:
      - ./config/kafka-ui/config.yml:/etc/kafkaui/dynamic_config.yaml
    depends_on:
      - kafka
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
